### ISSUE TITLE
still getting the pop-up menu when downloading PDFs

### ISSUE THREAD

**Issue by fabeit** [jscher2000/Content-Type-Fixer-extension#7]
I have the add-on active and I have selected open pdf with the pdf application but I still get the pop-up window in firefox quite often.

How can I troubleshoot this? I am on Waterfox if that makes any difference.

**Comment by jscher2000** [comment]
On the menu, try switching the

Content-Disposition Override

to "Allow viewing in a tab"

This overrides Content-Disposition: attachment, which triggers a download dialog even when you've set Firefox to open a file outside or save it automatically.

Does that work for your PDFs?

**Comment by jscher2000** [comment]
Note: In version 1.6 and later, that option changed to "Follow my settings (inline)".

**Comment by fabeit** [comment]
it seems the problem it's fixed! No more annoying pop-ups!

**Comment by jscher2000** [comment]
So for my test link, you get a download dialog: http://www.jeffersonscher.com/res/servepdf.php?f=Mixed_Content_Blocking.pdf

You could try switching the settings a few times. In the extension, switch between "As set by the server" and "Follow my settings (inline)" and in Firefox, switch between "Always ask" and "Use Adobe Acrobat" (or whatever your external program is named). See: https://support.mozilla.org/kb/view-pdf-files-firefox-or-choose-another-viewer 

Note that the extension cannot intercept blob files generated locally in a page by a script because it works by modifying responses from web servers. But otherwise, it should work.

**Comment by fabeit** [comment]
Thank you, it works on the download you have provided, even though Firefox gives a warning message that the file is flagged as a potential security risk. It is really strange how the dialogue still shows up even when the default PDF reader is selected in the Firefox settings. This bug has been around for as long as I can remember.
